services:
  database_postgres:
    image: 'postgres:17.5-alpine3.21'
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4:9.3.0'
    restart: unless-stopped
    env_file:
      - .env
    ports:
       - '8888:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - database_postgres

  python-backend:
    build:
      context: ./src/python-backend
    env_file:
      - ./src/python-backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - database_postgres

  java-backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database_postgres
      - python-backend

volumes:
  postgres_data:
  pgadmin_data: